---
- hosts: localhost
  tasks:
    - name: install java
      shell: sudo yum install java-1.8* -y

    - name: confirm java version
      shell: java -version

    - name: install wget
      shell: sudo yum install wget -y

    - name: install epel
      shell: sudo amazon-linux-extras install epel -y    

    - name: Download jenkins repo
      shell: sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

    - name: rpm
      shell: sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
    
    - name: install jenkins
      shell: sudo yum install jenkins -y

    - name: start jenkins
      shell: sudo systemctl start jenkins

    - name: Enable jenkins
      shell: sudo systemctl enable jenkins 

    - name: install git
      shell: sudo yum install git -y

